import Foundation
import Testing

@testable import MLXLMCommon

/// The ATEM envelope is generated by a model, not a serializer, and the
/// template itself warns that the output "is not expected to be valid XML".
/// These tests pin the well-formed shape and then push the malformed shapes
/// that have broken other families' parsers: stray `<` inside values, dropped
/// quotes, truncated envelopes, and orphan closers.
@Suite("ATEM tool-call parser")
struct ATEMToolCallParserTests {

    let parser = ATEMToolCallParser()

    /// Built from JSON rather than nested Swift literals: the literal form
    /// needs an `as [String: any Sendable]` cast at every level and the
    /// resulting diagnostics point at the wrong line.
    static let weatherTools: [[String: any Sendable]] = {
        let json = """
            [{
              "type": "function",
              "function": {
                "name": "get_weather",
                "parameters": {
                  "type": "object",
                  "properties": {
                    "city":   {"type": "string"},
                    "days":   {"type": "integer"},
                    "metric": {"type": "boolean"},
                    "tags":   {"type": "array", "items": {"type": "string"}}
                  }
                }
              }
            }]
            """
        let parsed = try! JSONSerialization.jsonObject(with: Data(json.utf8))
        return (parsed as! [[String: Any]]).map { $0.mapValues { asSendable($0) } }
    }()

    func envelope(_ body: String) -> String {
        "<atem:function_calls>\n\(body)\n</atem:function_calls>"
    }

    // MARK: - Well-formed

    @Test("parses a single invoke with schema-typed parameters")
    func parsesSingleInvoke() {
        let content = envelope("""
            <atem:invoke name="get_weather">
            <atem:parameter name="city">Paris</atem:parameter>
            <atem:parameter name="days">3</atem:parameter>
            <atem:parameter name="metric">true</atem:parameter>
            <atem:parameter name="tags">["a", "b"]</atem:parameter>
            </atem:invoke>
            """)

        let call = parser.parse(content: content, tools: Self.weatherTools)
        #expect(call?.function.name == "get_weather")
        #expect(call?.function.arguments["city"] == .string("Paris"))
        #expect(call?.function.arguments["days"] == .int(3))
        #expect(call?.function.arguments["metric"] == .bool(true))
        #expect(call?.function.arguments["tags"] == .array([.string("a"), .string("b")]))
    }

    @Test("one envelope carrying several invokes yields every call at EOS")
    func parsesParallelInvokes() {
        let content = envelope("""
            <atem:invoke name="get_weather">
            <atem:parameter name="city">Paris</atem:parameter>
            </atem:invoke>
            <atem:invoke name="get_weather">
            <atem:parameter name="city">Tokyo</atem:parameter>
            </atem:invoke>
            """)

        let calls = parser.parseEOS(content, tools: Self.weatherTools)
        #expect(calls.count == 2)
        #expect(calls.first?.function.arguments["city"] == .string("Paris"))
        #expect(calls.last?.function.arguments["city"] == .string("Tokyo"))
        // `parse` keeps the single-call contract but must not lose the first.
        #expect(parser.parse(content: content, tools: Self.weatherTools)?
            .function.arguments["city"] == .string("Paris"))
    }

    // MARK: - Malformed / adversarial

    @Test("a value containing < and > does not desync tag detection")
    func toleratesAngleBracketsInsideValues() {
        // The gemma4 failure mode: a stray '<' inside the body made the
        // detector lose the envelope and leak protocol text to the user.
        let content = envelope("""
            <atem:invoke name="get_weather">
            <atem:parameter name="city">a < b and c > d <notatag></atem:parameter>
            </atem:invoke>
            """)

        let call = parser.parse(content: content, tools: Self.weatherTools)
        #expect(call?.function.name == "get_weather")
        #expect(call?.function.arguments["city"] == .string("a < b and c > d <notatag>"))
    }

    @Test("unquoted name attributes still resolve")
    func toleratesMissingQuotes() {
        let content = envelope("""
            <atem:invoke name=get_weather>
            <atem:parameter name=city>Oslo</atem:parameter>
            </atem:invoke>
            """)

        let call = parser.parse(content: content, tools: Self.weatherTools)
        #expect(call?.function.name == "get_weather")
        #expect(call?.function.arguments["city"] == .string("Oslo"))
    }

    @Test("a truncated envelope still yields the parameters that completed")
    func recoversFromTruncation() {
        // Generation cut off mid-envelope: no closing tags at all.
        let content = """
            <atem:function_calls>
            <atem:invoke name="get_weather">
            <atem:parameter name="city">Lisbon</atem:parameter>
            """

        let calls = parser.parseEOS(content, tools: Self.weatherTools)
        #expect(calls.count == 1)
        #expect(calls.first?.function.arguments["city"] == .string("Lisbon"))
    }

    @Test("malformed JSON in an array parameter degrades to the raw string")
    func malformedJSONDoesNotCrash() {
        let content = envelope("""
            <atem:invoke name="get_weather">
            <atem:parameter name="tags">["a", "b</atem:parameter>
            </atem:invoke>
            """)

        // The point is that it neither throws nor drops the call — the
        // downstream schema error is a better failure than a lost tool call.
        let call = parser.parse(content: content, tools: Self.weatherTools)
        #expect(call?.function.name == "get_weather")
        #expect(call?.function.arguments["tags"] != nil)
    }

    @Test("an invoke with no name is skipped without losing later calls")
    func skipsNamelessInvoke() {
        let content = envelope("""
            <atem:invoke>
            <atem:parameter name="city">Ghost</atem:parameter>
            </atem:invoke>
            <atem:invoke name="get_weather">
            <atem:parameter name="city">Real</atem:parameter>
            </atem:invoke>
            """)

        let calls = parser.parseEOS(content, tools: Self.weatherTools)
        #expect(calls.count == 1)
        #expect(calls.first?.function.arguments["city"] == .string("Real"))
    }

    @Test("empty and unparseable envelopes yield no calls rather than a crash")
    func emptyEnvelopeYieldsNothing() {
        #expect(parser.parseEOS(envelope(""), tools: Self.weatherTools).isEmpty)
        #expect(parser.parseEOS("", tools: Self.weatherTools).isEmpty)
        #expect(parser.parse(content: "just prose", tools: Self.weatherTools) == nil)
    }

    // MARK: - Streaming behavior

    @Test("orphan closers are registered so they never reach visible text")
    func orphanClosersRegistered() {
        // A stray closer run after an agent-loop step must be stripped, not
        // streamed — the ZAYA/gemma4 regression class.
        #expect(parser.orphanStripTags.contains("</atem:function_calls>"))
        #expect(parser.orphanStripTags.contains("</atem:invoke>"))
        #expect(parser.orphanStripTags.contains("</atem:parameter>"))
    }

    @Test("partial-content gate buffers the opener but rejects ordinary prose")
    func partialContentGate() {
        #expect(parser.isValidPartialContent("<atem:"))
        #expect(parser.isValidPartialContent("<atem:function_calls>"))
        #expect(parser.isValidPartialContent("<atem:function_calls>\n<atem:invoke"))
        // Prose that merely mentions the tag must not be buffered forever.
        #expect(parser.isValidPartialContent("the <atem: syntax is") == false)
        #expect(parser.isValidPartialContent("hello") == false)
    }

    // MARK: - Format wiring

    @Test("muse_glimmer and atem stamps both resolve to the ATEM parser")
    func formatStampsResolve() {
        for stamp in ["atem", "onyx_atem", "muse_glimmer", "muse"] {
            let format = ToolCallFormat.fromCapabilityName(stamp)
            #expect(format == .atem, "stamp \(stamp) should map to .atem")
        }
        #expect(ToolCallFormat.atem.createParser() is ATEMToolCallParser)
        #expect(ToolCallFormat.atem.hasTaggedToolMarkers)
    }
}
